var k;k||=typeof Immolate != 'undefined' ? Immolate : {};var aa="object"==typeof window,p="undefined"!=typeof WorkerGlobalScope,q="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,r=p&&self.name?.startsWith("em-pthread");if(q){var ba=require("worker_threads");global.Worker=ba.Worker;r=(p=!ba.$a)&&"em-pthread"==ba.workerData}var ca=(a,b)=>{throw b;},da="undefined"!=typeof document?document.currentScript?.src:void 0;
"undefined"!=typeof __filename?da=__filename:p&&(da=self.location.href);var ea="",fa,ha;
if(q){var fs=require("fs");ea=__dirname+"/";ha=a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);ca=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||p){try{ea=(new URL(".",da)).href}catch{}q||(p&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=async a=>{if(ia(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);})}var ja=console.log.bind(console),ka=console.error.bind(console);
if(q){var la=require("util"),ma=a=>"object"==typeof a?la.inspect(a):a;ja=(...a)=>fs.writeSync(1,a.map(ma).join(" ")+"\n");ka=(...a)=>fs.writeSync(2,a.map(ma).join(" ")+"\n")}var na=ja,u=ka,z,oa,pa=!1,qa,ia=a=>a.startsWith("file://");if(q&&r){var ra=ba.parentPort;ra.on("message",a=>global.onmessage?.({data:a}));Object.assign(globalThis,{self:global,postMessage:a=>ra.postMessage(a)});process.on("uncaughtException",a=>{postMessage({pa:"uncaughtException",error:a});process.exit(1)})}var sa;
if(r){var ta=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.pa;if("load"===d){let e=[];self.onmessage=f=>e.push(f);sa=()=>{postMessage({pa:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Oa)if(!k[f]||k[f].proxy)k[f]=(...g)=>{postMessage({pa:"callHandler",Na:f,args:g})},"print"==f&&(na=k[f]),"printErr"==f&&(u=k[f]);A=c.Ya;ua();oa=c.Za;va();wa()}else if("run"===d){xa(c.qa);ya(c.qa,0,0,1,0,0);za();Aa(c.qa);ta||(Ba(),ta=!0);try{Ca(c.Wa,c.Ca)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ta&&Da():d&&(u(`worker: received unknown command ${d}`),u(c)))}catch(e){throw Ea(),e;}}self.onmessage=a}var A,Fa,C,Ga,D,E,F,Ha,Ia,G,Ja;function ua(){var a=A.buffer;Fa=new Int8Array(a);Ga=new Int16Array(a);C=new Uint8Array(a);D=new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);Ha=new Float32Array(a);Ia=new Float64Array(a);G=new BigInt64Array(a);Ja=new BigUint64Array(a)}function Ka(){r?sa():H.M()}
function La(a){k.onAbort?.(a);a="Aborted("+a+")";u(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ma;async function Na(a){if(!z)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==Ma&&z)a=new Uint8Array(z);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Oa(a,b){try{var c=await Na(a);return await WebAssembly.instantiate(c,b)}catch(d){u(`failed to asynchronously prepare wasm: ${d}`),La(d)}}async function Pa(a){var b=Ma;if(!z&&!ia(b)&&!q)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){u(`wasm streaming compile failed: ${d}`),u("falling back to ArrayBuffer instantiation")}return Oa(b,a)}
function Qa(){Ra={i:Ta,p:Ua,C:Va,z:Wa,w:Xa,K:Ya,f:Za,d:$a,b:ab,c:bb,x:cb,I:db,v:eb,k:fb,g:gb,e:hb,j:ib,J:jb,o:kb,L:lb,F:mb,B:nb,D:ob,r:pb,E:Aa,u:qb,h:rb,m:sb,l:tb,s:ub,G:vb,n:wb,A:xb,H:yb,t:zb,q:Ab,a:A,y:Bb};return{a:Ra}}
async function va(){function a(d,e){H=d.exports;Cb.push(H.T);Db=H.P;oa=e;d=H;Eb=d.N;Ba=d.O;Fb=d.Q;Gb=d.R;k._main=d.S;k.__emscripten_proxy_main=Hb=d.U;ya=d.V;Ea=d.W;I=d.X;Ib=d.Y;Jb=d.Z;Kb=d._;Lb=d.$;Mb=d.aa;Nb=d.ba;Ob=d.ca;Pb=d.da;K--;k.monitorRunDependencies?.(K);0==K&&Qb&&(d=Qb,Qb=null,d());return H}K++;k.monitorRunDependencies?.(K);var b=Qa();if(k.instantiateWasm)new Promise(d=>{k.instantiateWasm(b,(e,f)=>{d(a(e,f))})});else if(r){var c=new WebAssembly.Instance(oa,Qa());a(c,oa)}else Ma??=k.locateFile?
k.locateFile("immolate.wasm",ea):ea+"immolate.wasm",function(d){return a(d.instance,d.module)}(await Pa(b))}class Rb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Sb=a=>{a.terminate();a.onmessage=()=>{}},Tb=a=>{for(;0<a.length;)a.shift()(k)},Ub=[],Vb=()=>{var a=k.preRun.shift();Ub.push(a)},Yb=a=>{if(0==L.length){var b=da;k.mainScriptUrlOrBlob&&(b=k.mainScriptUrlOrBlob,"string"!=typeof b&&(b=URL.createObjectURL(b)));b=new Worker(b,{workerData:"em-pthread",name:"em-pthread"});L.push(b);Wb()}b=L.pop();if(!b)return 6;Xb.push(b);M[a.qa]=b;b.qa=a.qa;var c={pa:"run",Wa:a.Va,Ca:a.Ca,qa:a.qa};q&&b.unref();b.postMessage(c,a.Ia);return 0},N=0,yb=()=>O||0<N,$b=(a,
b,...c)=>{for(var d=2*c.length,e=Pb(),f=Ob(8*d),g=f>>3,h=0;h<c.length;h++){var l=c[h];"bigint"==typeof l?(G[g+2*h]=1n,G[g+2*h+1]=l):(G[g+2*h]=0n,Ia[g+2*h+1]=l)}a=Ib(a,0,d,f,b);Nb(e);return a};function ac(a){if(r)return $b(0,1,a);qa=a;if(!(O||0<N)){for(var b of Xb)Sb(b);for(b of L)Sb(b);L=[];Xb=[];M={};k.onExit?.(a);pa=!0}ca(a,new Rb(a))}function bc(a){if(r)return $b(1,0,a);--N;zb(a)}
var zb=a=>{qa=a;if(r)throw bc(a),"unwind";ac(a)},L=[],Xb=[],Cb=[],M={},cc=a=>{var b=a.qa;delete M[b];L.push(a);Xb.splice(Xb.indexOf(a),1);a.qa=0;q&&a.unref();Jb(b)};function za(){Cb.forEach(a=>a())}
var Wb=()=>{var a=L[0];new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.pa;if(g.Ba&&g.Ba!=Fb()){var h=M[g.Ba];h?h.postMessage(g,g.Ia):u(`Internal error! Worker sent a message "${f}" to target pthread ${g.Ba}, but that thread no longer exists!`)}else if("checkMailbox"===f)Da();else if("spawnThread"===f)Yb(g);else if("cleanupThread"===f)dc(()=>{cc(M[g.Xa])});else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("uncaughtException"===f)a.onerror(g.error);else if("callHandler"===
f)k[g.Na](...g.args);else f&&u(`worker sent an unknown command ${f}`)};a.onerror=f=>{u(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};q&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)k.propertyIsEnumerable(e)&&c.push(e);a.postMessage({pa:"load",Oa:c,Ya:A,Za:oa})})},ec=[],K=0,Qb=null;function xa(a){var b=F[a+52>>2];Mb(b,b-F[a+56>>2]);Nb(b)}
var fc=[],Db,gc=a=>{var b=fc[a];b||(fc[a]=b=Db.get(a));return b},Ca=(a,b)=>{O=N=0;a=gc(a)(b);O||0<N?qa=a:Kb(a)},O=!0,hc="undefined"!=typeof TextDecoder?new TextDecoder:void 0,ic=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},jc=(a,b=0,c,d)=>{c=ic(a,b,c,d);if(16<c-b&&a.buffer&&hc)return hc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&
63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ta=(a,b,c,d)=>La(`Assertion failed: ${a?jc(C,a):""}, at: `+[b?b?jc(C,b):"":"unknown filename",c,d?d?jc(C,d):"":"unknown function"]);class kc{constructor(a){this.ga=a-24}}var lc=0,mc=0,Ua=(a,b,c)=>{var d=new kc(a);F[d.ga+16>>2]=0;F[d.ga+4>>2]=b;F[d.ga+8>>2]=c;lc=a;mc++;throw lc;};
function nc(a,b,c,d){return r?$b(2,1,a,b,c,d):Va(a,b,c,d)}var Va=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return nc(a,b,c,d);a={Va:c,qa:a,Ca:d,Ia:e};return r?(a.pa="spawnThread",postMessage(a,e),0):Yb(a)},Wa=()=>La(""),R=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},S={},T={},oc={},U=class extends Error{constructor(a){super(a);this.name="BindingError"}},pc=a=>{throw new U(a);};
function qc(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(T.hasOwnProperty(a)){if(c.Pa)return;throw new U(`Cannot register type '${d}' twice`);}T[a]=b;delete oc[a];S.hasOwnProperty(a)&&(b=S[a],delete S[a],b.forEach(e=>e()))}function V(a,b,c={}){return qc(a,b,c)}
var rc=(a,b,c)=>{switch(b){case 1:return c?d=>Fa[d]:d=>C[d];case 2:return c?d=>Ga[d>>1]:d=>D[d>>1];case 4:return c?d=>E[d>>2]:d=>F[d>>2];case 8:return c?d=>G[d>>3]:d=>Ja[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Xa=(a,b,c,d,e)=>{b=R(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}V(a,{name:b,ia:f,ma:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},ra:rc(b,c,!d),oa:null})},Ya=(a,b,c,d)=>{b=R(b);V(a,{name:b,ia:function(e){return!!e},ma:function(e,
f){return f?c:d},ra:function(e){return this.ia(C[e])},oa:null})},sc=a=>{throw new U(a.ea.ha.fa.name+" instance already deleted");},tc=!1,uc=()=>{},vc=a=>{if("undefined"===typeof FinalizationRegistry)return vc=b=>b,a;tc=new FinalizationRegistry(b=>{b=b.ea;--b.count.value;0===b.count.value&&(b.ka?b.na.ta(b.ka):b.ha.fa.ta(b.ga))});vc=b=>{var c=b.ea;c.ka&&tc.register(b,{ea:c},b);return b};uc=b=>{tc.unregister(b)};return vc(a)},wc=[];function xc(){}
var yc=(a,b)=>Object.defineProperty(b,"name",{value:a}),zc={},Ac=(a,b,c)=>{if(void 0===a[b].ja){var d=a[b];a[b]=function(...e){if(!a[b].ja.hasOwnProperty(e.length))throw new U(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ja})!`);return a[b].ja[e.length].apply(this,e)};a[b].ja=[];a[b].ja[d.va]=d}},Bc=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].ja&&void 0!==k[a].ja[c])throw new U(`Cannot register public name '${a}' twice`);Ac(k,
a,a);if(k[a].ja.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);k[a].ja[c]=b}else k[a]=b,k[a].va=c},Cc=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Dc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.sa=c;this.ta=d;this.la=e;this.La=f;this.ya=g;this.Ka=h;this.Ra=[]}
var Ec=(a,b,c)=>{for(;b!==c;){if(!b.ya)throw new U(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ya(a);b=b.la}return a},Fc=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Gc(a,b){if(null===b){if(this.Da)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.ea)throw new U(`Cannot pass "${Fc(b)}" as a ${this.name}`);if(!b.ea.ga)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);return Ec(b.ea.ga,b.ea.ha.fa,this.fa)}
function Hc(a,b){if(null===b){if(this.Da)throw new U(`null is not a valid ${this.name}`);if(this.Aa){var c=this.Sa();null!==a&&a.push(this.ta,c);return c}return 0}if(!b||!b.ea)throw new U(`Cannot pass "${Fc(b)}" as a ${this.name}`);if(!b.ea.ga)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.za&&b.ea.ha.za)throw new U(`Cannot convert argument of type ${b.ea.na?b.ea.na.name:b.ea.ha.name} to parameter type ${this.name}`);c=Ec(b.ea.ga,b.ea.ha.fa,this.fa);if(this.Aa){if(void 0===
b.ea.ka)throw new U("Passing raw pointer to smart pointer is illegal");switch(this.Ua){case 0:if(b.ea.na===this)c=b.ea.ka;else throw new U(`Cannot convert argument of type ${b.ea.na?b.ea.na.name:b.ea.ha.name} to parameter type ${this.name}`);break;case 1:c=b.ea.ka;break;case 2:if(b.ea.na===this)c=b.ea.ka;else{var d=b.clone();c=this.Ta(c,Ic(()=>d["delete"]()));null!==a&&a.push(this.ta,c)}break;default:throw new U("Unsupporting sharing policy");}}return c}
function Jc(a,b){if(null===b){if(this.Da)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.ea)throw new U(`Cannot pass "${Fc(b)}" as a ${this.name}`);if(!b.ea.ga)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.ea.ha.za)throw new U(`Cannot convert argument of type ${b.ea.ha.name} to parameter type ${this.name}`);return Ec(b.ea.ga,b.ea.ha.fa,this.fa)}function Kc(a){return this.ia(F[a>>2])}
var Lc=(a,b,c)=>{if(b===c)return a;if(void 0===c.la)return null;a=Lc(a,b,c.la);return null===a?null:c.Ka(a)},Mc={},Nc=(a,b)=>{if(void 0===b)throw new U("ptr should not be undefined");for(;a.la;)b=a.ya(b),a=a.la;return Mc[b]},Oc=class extends Error{constructor(a){super(a);this.name="InternalError"}},Pc=(a,b)=>{if(!b.ha||!b.ga)throw new Oc("makeClassHandle requires ptr and ptrType");if(!!b.na!==!!b.ka)throw new Oc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return vc(Object.create(a,
{ea:{value:b,writable:!0}}))};function Qc(a,b,c,d,e,f,g,h,l,n,m){this.name=a;this.fa=b;this.Da=c;this.za=d;this.Aa=e;this.Qa=f;this.Ua=g;this.Ha=h;this.Sa=l;this.Ta=n;this.ta=m;e||void 0!==b.la?this.ma=Hc:(this.ma=d?Gc:Jc,this.oa=null)}
var Rc=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new Oc("Replacing nonexistent public symbol");void 0!==k[a].ja&&void 0!==c?k[a].ja[c]=b:(k[a]=b,k[a].va=c)},W=(a,b)=>{a=R(a);var c=gc(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};class Sc extends Error{}
var Tc=a=>{a=Eb(a);var b=R(a);I(a);return b},X=(a,b)=>{function c(f){e[f]||T[f]||(oc[f]?oc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Sc(`${a}: `+d.map(Tc).join([", "]));},Y=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Oc("Mismatched type converter count");for(var l=0;l<a.length;++l)V(a[l],h[l])}a.forEach(h=>oc[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,l)=>{T.hasOwnProperty(h)?e[l]=T[h]:(f.push(h),S.hasOwnProperty(h)||(S[h]=[]),S[h].push(()=>
{e[l]=T[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Za=(a,b,c,d,e,f,g,h,l,n,m,t,x)=>{m=R(m);f=W(e,f);h&&=W(g,h);n&&=W(l,n);x=W(t,x);var v=Cc(m);Bc(v,function(){X(`Cannot construct ${m} due to unbound types`,[d])});Y([a,b,c],d?[d]:[],w=>{w=w[0];if(d){var y=w.fa;var P=y.sa}else P=xc.prototype;w=yc(m,function(...Sa){if(Object.getPrototypeOf(this)!==Q)throw new U(`Use 'new' to construct ${m}`);if(void 0===B.ua)throw new U(`${m} has no accessible constructor`);var Zb=B.ua[Sa.length];if(void 0===
Zb)throw new U(`Tried to invoke ctor of ${m} with invalid number of parameters (${Sa.length}) - expected (${Object.keys(B.ua).toString()}) parameters instead!`);return Zb.apply(this,Sa)});var Q=Object.create(P,{constructor:{value:w}});w.prototype=Q;var B=new Dc(m,w,Q,x,y,f,h,n);if(B.la){var J;(J=B.la).Ea??(J.Ea=[]);B.la.Ea.push(B)}y=new Qc(m,B,!0,!1,!1);J=new Qc(m+"*",B,!1,!1,!1);P=new Qc(m+" const*",B,!1,!0,!1);zc[a]={pointerType:J,Ja:P};Rc(v,w);return[y,J,P]})},Uc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F[b+
4*d>>2]);return c},Vc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Wc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].oa)return!0;return!1}
function Xc(a,b,c,d,e,f){var g=b.length;if(2>g)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=Wc(b);c=!b[0].Ga;var n=b[0],m=b[1];d=[a,pc,d,e,Vc,n.ia.bind(n),m?.ma.bind(m)];for(e=2;e<g;++e)n=b[e],d.push(n.ma.bind(n));if(!l)for(e=h?1:2;e<b.length;++e)null!==b[e].oa&&d.push(b[e].oa);l=Wc(b);e=b.length-2;m=[];n=["fn"];h&&n.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),n.push(`arg${g}Wired`);m=m.join(",");n=n.join(",");
m=`return function (${m}) {\n`;l&&(m+="var destructors = [];\n");var t=l?"destructors":"null",x="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${t}, this);\n`);for(g=0;g<e;++g){var v=`toArg${g}Wire`;m+=`var arg${g}Wired = ${v}(${t}, arg${g});\n`;x.push(v)}m+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(l)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].oa&&(m+=`${f}_dtor(${f});\n`,x.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(x,m+"}\n"))(...d);return yc(a,b)}
var $a=(a,b,c,d,e,f)=>{var g=Uc(b,c);e=W(d,e);Y([],[a],h=>{h=h[0];var l=`constructor ${h.name}`;void 0===h.fa.ua&&(h.fa.ua=[]);if(void 0!==h.fa.ua[b-1])throw new U(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.fa.ua[b-1]=()=>{X(`Cannot construct ${h.name} due to unbound types`,g)};Y([],g,n=>{n.splice(1,0,null);h.fa.ua[b-1]=Xc(l,n,null,e,
f);return[]});return[]})},Yc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},ab=(a,b,c,d,e,f,g,h,l)=>{var n=Uc(c,d);b=R(b);b=Yc(b);f=W(e,f);Y([],[a],m=>{function t(){X(`Cannot call ${x} due to unbound types`,n)}m=m[0];var x=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.fa.Ra.push(b);var v=m.fa.sa,w=v[b];void 0===w||void 0===w.ja&&w.className!==m.name&&w.va===c-2?(t.va=c-2,t.className=m.name,v[b]=t):(Ac(v,b,x),v[b].ja[c-2]=t);Y([],n,y=>{y=Xc(x,y,m,f,g,l);void 0===
v[b].ja?(y.va=c-2,v[b]=y):v[b].ja[c-2]=y;return[]});return[]})},Zc=(a,b,c)=>{if(!(a instanceof Object))throw new U(`${c} with invalid "this": ${a}`);if(!(a instanceof b.fa.constructor))throw new U(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.ea.ga)throw new U(`cannot call emscripten binding method ${c} on deleted object`);return Ec(a.ea.ga,a.ea.ha.fa,b.fa)},bb=(a,b,c,d,e,f,g,h,l,n)=>{b=R(b);e=W(d,e);Y([],[a],m=>{m=m[0];var t=`${m.name}.${b}`,x={get(){X(`Cannot access ${t} due to unbound types`,
[c,g])},enumerable:!0,configurable:!0};x.set=l?()=>X(`Cannot access ${t} due to unbound types`,[c,g]):()=>{throw new U(t+" is a read-only property");};Object.defineProperty(m.fa.sa,b,x);Y([],l?[c,g]:[c],v=>{var w=v[0],y={get(){var Q=Zc(this,m,t+" getter");return w.ia(e(f,Q))},enumerable:!0};if(l){l=W(h,l);var P=v[1];y.set=function(Q){var B=Zc(this,m,t+" setter"),J=[];l(n,B,P.ma(J,Q));Vc(J)}}Object.defineProperty(m.fa.sa,b,y);return[]});return[]})},cb=(a,b,c)=>{a=R(a);Y([],[b],d=>{d=d[0];k[a]=d.ia(c);
return[]})},$c=[],Z=[0,1,,1,null,1,!0,1,!1,1],ad=a=>{9<a&&0===--Z[a+1]&&(Z[a]=void 0,$c.push(a))},bd=a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);return Z[a]},Ic=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=$c.pop()||Z.length;Z[b]=a;Z[b+1]=1;return b}},cd={name:"emscripten::val",ia:a=>{var b=bd(a);ad(a);return b},ma:(a,b)=>Ic(b),ra:Kc,oa:null},db=a=>V(a,cd),dd=(a,b)=>{switch(b){case 4:return function(c){return this.ia(Ha[c>>
2])};case 8:return function(c){return this.ia(Ia[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},eb=(a,b,c)=>{b=R(b);V(a,{name:b,ia:d=>d,ma:(d,e)=>e,ra:dd(b,c),oa:null})},fb=(a,b,c,d,e,f,g)=>{var h=Uc(b,c);a=R(a);a=Yc(a);e=W(d,e);Bc(a,function(){X(`Cannot call ${a} due to unbound types`,h)},b-1);Y([],h,l=>{l=[l[0],null].concat(l.slice(1));Rc(a,Xc(a,l,null,e,f,g),b-1);return[]})},gb=(a,b,c,d,e)=>{b=R(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}V(a,{name:b,ia:f,
ma:(h,l)=>l,ra:rc(b,c,0!==d),oa:null})},hb=(a,b,c)=>{function d(f){return new e(Fa.buffer,F[f+4>>2],F[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c);V(a,{name:c,ia:d,ra:d},{Pa:!0})},ed=Object.assign({optional:!0},cd),ib=a=>{V(a,ed)},jb=(a,b)=>{b=R(b);V(a,{name:b,ia(c){var d=(d=c+4)?jc(C,d,F[c>>2],!0):"";I(c);return d},ma(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;
if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var g;if(f)for(e=g=0;e<d.length;++e){var h=d.charCodeAt(e);127>=h?g++:2047>=h?g+=2:55296<=h&&57343>=h?(g+=4,++e):g+=3}else g=d.length;e=g;g=Gb(4+e+1);h=g+4;F[g>>2]=e;if(f){if(f=h,h=e+1,e=C,0<h){h=f+h-1;for(var l=0;l<d.length;++l){var n=d.codePointAt(l);if(127>=n){if(f>=h)break;e[f++]=n}else if(2047>=n){if(f+1>=h)break;e[f++]=192|n>>6;e[f++]=128|n&63}else if(65535>=n){if(f+2>=h)break;e[f++]=
224|n>>12;e[f++]=128|n>>6&63;e[f++]=128|n&63}else{if(f+3>=h)break;e[f++]=240|n>>18;e[f++]=128|n>>12&63;e[f++]=128|n>>6&63;e[f++]=128|n&63;l++}}e[f]=0}}else C.set(d,h);null!==c&&c.push(I,g);return g},ra:Kc,oa(c){I(c)}})},fd="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,gd=(a,b,c)=>{a>>=1;b=ic(D,a,b/2,c);if(16<b-a&&fd)return fd.decode(D.buffer instanceof ArrayBuffer?D.subarray(a,b):D.slice(a,b));for(c="";a<b;++a)c+=String.fromCharCode(D[a]);return c},hd=(a,b,c)=>{c??=2147483647;
if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)Ga[b>>1]=a.charCodeAt(e),b+=2;Ga[b>>1]=0;return b-d},jd=a=>2*a.length,kd=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=F[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},ld=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d},md=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&
c++,b+=4;return b},kb=(a,b,c)=>{c=R(c);if(2===b){var d=gd;var e=hd;var f=jd}else d=kd,e=ld,f=md;V(a,{name:c,ia:g=>{var h=d(g+4,F[g>>2]*b,!0);I(g);return h},ma:(g,h)=>{if("string"!=typeof h)throw new U(`Cannot pass non-string to C++ string type ${c}`);var l=f(h),n=Gb(4+l+b);F[n>>2]=l/b;e(h,n+4,l+b);null!==g&&g.push(I,n);return n},ra:Kc,oa(g){I(g)}})},lb=(a,b)=>{b=R(b);V(a,{Ga:!0,name:b,ia:()=>{},ma:()=>{}})},mb=a=>{ya(a,!p,1,!aa,65536,!1);za()},nd=a=>{a instanceof Rb||"unwind"==a||ca(1,a)},dc=a=>{if(!pa)try{if(a(),
!(O||0<N))try{r?Fb()&&Kb(qa):zb(qa)}catch(b){nd(b)}}catch(b){nd(b)}},Aa=a=>{"function"===typeof Atomics.waitAsync&&(Atomics.waitAsync(E,a>>2,a).value.then(Da),Atomics.store(E,a+128>>2,1))},Da=()=>dc(()=>{var a=Fb();a&&(Aa(a),Lb())}),nb=(a,b)=>{a==b?setTimeout(Da):r?postMessage({Ba:a,pa:"checkMailbox"}):(a=M[a])&&a.postMessage({pa:"checkMailbox"})},od=[],ob=(a,b,c,d,e)=>{d/=2;od.length=d;b=e>>3;for(c=0;c<d;c++)od[c]=G[b+2*c]?G[b+2*c+1]:Ia[b+2*c+1];return(0,pd[a])(...od)},pb=a=>{r?postMessage({pa:"cleanupThread",
Xa:a}):cc(M[a])},qb=a=>{q&&M[a].ref()},qd=[],rd=a=>{var b=qd.length;qd.push(a);return b},sd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=F[b+4*d>>2],g=T[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${Tc(f)}`,new U(a);c[e]=g}return c},td=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(F[b>>2]=Ic(d));return a},ud={},vd=a=>{var b=ud[a];return void 0===b?R(a):b},rb=(a,b,c)=>{var [d,...e]=sd(a,b);b=d.ma.bind(d);var f=e.map(l=>l.ra.bind(l));a--;var g={toValue:bd};a=f.map((l,n)=>{var m=`argFromPtr${n}`;
g[m]=l;return`${m}(args${n?"+"+8*n:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=vd,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.Ga||(g.toReturnWire=b,g.emval_returnValue=td,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(l=>
l.name)}) => ${d.name}>`;return rd(yc(h,c))},sb=(a,b,c,d,e)=>qd[a](b,c,d,e),tb=a=>{var b=bd(a);Vc(b);ad(a)},wb=()=>performance.timeOrigin+performance.now(),ub=()=>{},vb=()=>{N+=1;throw"unwind";},xb=()=>{La("OOM")},wd=[null,[],[]];function Ab(a,b,c,d){if(r)return $b(3,1,a,b,c,d);for(var e=0,f=0;f<c;f++){var g=F[b>>2],h=F[b+4>>2];b+=8;for(var l=0;l<h;l++){var n=a,m=C[g+l],t=wd[n];0===m||10===m?((1===n?na:u)(jc(t)),t.length=0):t.push(m)}e+=h}F[d>>2]=e;return 0}
var xd=()=>{if(q){var a=require("crypto");return b=>a.randomFillSync(b)}return b=>b.set(crypto.getRandomValues(new Uint8Array(b.byteLength)))},yd=a=>{(yd=xd())(a)},Bb=(a,b)=>{yd(C.subarray(a,a+b));return 0};
(()=>{let a=xc.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof xc&&c instanceof xc))return!1;var d=this.ea.ha.fa,e=this.ea.ga;c.ea=c.ea;var f=c.ea.ha.fa;for(c=c.ea.ga;d.la;)e=d.ya(e),d=d.la;for(;f.la;)c=f.ya(c),f=f.la;return d===f&&e===c},clone:function(){this.ea.ga||sc(this);if(this.ea.xa)return this.ea.count.value+=1,this;var c=vc,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.ea;c=c(e.call(d,f,{ea:{value:{count:g.count,wa:g.wa,xa:g.xa,ga:g.ga,ha:g.ha,ka:g.ka,na:g.na}}}));
c.ea.count.value+=1;c.ea.wa=!1;return c},["delete"](){this.ea.ga||sc(this);if(this.ea.wa&&!this.ea.xa)throw new U("Object already scheduled for deletion");uc(this);var c=this.ea;--c.count.value;0===c.count.value&&(c.ka?c.na.ta(c.ka):c.ha.fa.ta(c.ga));this.ea.xa||(this.ea.ka=void 0,this.ea.ga=void 0)},isDeleted:function(){return!this.ea.ga},deleteLater:function(){this.ea.ga||sc(this);if(this.ea.wa&&!this.ea.xa)throw new U("Object already scheduled for deletion");wc.push(this);this.ea.wa=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(Qc.prototype,{Ma(a){this.Ha&&(a=this.Ha(a));return a},Fa(a){this.ta?.(a)},ra:Kc,ia:function(a){function b(){return this.Aa?Pc(this.fa.sa,{ha:this.Qa,ga:c,na:this,ka:a}):Pc(this.fa.sa,{ha:this,ga:a})}var c=this.Ma(a);if(!c)return this.Fa(a),null;var d=Nc(this.fa,c);if(void 0!==d){if(0===d.ea.count.value)return d.ea.ga=c,d.ea.ka=a,d.clone();d=d.clone();this.Fa(a);return d}d=this.fa.La(c);d=zc[d];if(!d)return b.call(this);d=this.za?d.Ja:d.pointerType;var e=Lc(c,this.fa,d.fa);return null===
e?b.call(this):this.Aa?Pc(d.fa.sa,{ha:d,ga:e,na:this,ka:a}):Pc(d.fa.sa,{ha:d,ga:e})}});if(!r){if(k.wasmMemory)A=k.wasmMemory;else{var zd=k.INITIAL_MEMORY||16777216;A=new WebAssembly.Memory({initial:zd/65536,maximum:zd/65536,shared:!0})}ua()}k.noExitRuntime&&(O=k.noExitRuntime);k.print&&(na=k.print);k.printErr&&(u=k.printErr);k.wasmBinary&&(z=k.wasmBinary);if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();
var pd=[ac,bc,nc,Ab],Eb,Ba,Fb,Gb,Hb,ya,Ea,I,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Pb,Ra;
function wa(){function a(){k.calledRun=!0;if(!pa){Ka();k.onRuntimeInitialized?.();if(!k.noInitialRun){var b=Hb;N+=1;try{var c=b(0,0);zb(c,!0)}catch(d){nd(d)}}if(!r){if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),ec.push(b);Tb(ec)}}}if(0<K)Qb=wa;else if(r)Ka();else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Vb();Tb(Ub);0<K?Qb=wa:k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>
k.setStatus(""),1);a()},1)):a()}}var H;r||(va(),wa());
