var k;k||=typeof Immolate != 'undefined' ? Immolate : {};var aa="object"==typeof window,p="undefined"!=typeof WorkerGlobalScope,q="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,r=p&&self.name?.startsWith("em-pthread");if(q){var ba=require("worker_threads");global.Worker=ba.Worker;r=(p=!ba.Za)&&"em-pthread"==ba.workerData}var ca=(a,b)=>{throw b;},da="undefined"!=typeof document?document.currentScript?.src:void 0;
"undefined"!=typeof __filename?da=__filename:p&&(da=self.location.href);var ea="",fa,ha;
if(q){var fs=require("fs");ea=__dirname+"/";ha=a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=ia(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);ca=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||p){try{ea=(new URL(".",da)).href}catch{}q||(p&&(ha=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),fa=async a=>{if(ia(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);})}var ja=console.log.bind(console),ka=console.error.bind(console);
if(q){var la=require("util"),ma=a=>"object"==typeof a?la.inspect(a):a;ja=(...a)=>fs.writeSync(1,a.map(ma).join(" ")+"\n");ka=(...a)=>fs.writeSync(2,a.map(ma).join(" ")+"\n")}var na=ja,u=ka,z,oa,pa=!1,qa,ia=a=>a.startsWith("file://");if(q&&r){var ra=ba.parentPort;ra.on("message",a=>global.onmessage?.({data:a}));Object.assign(globalThis,{self:global,postMessage:a=>ra.postMessage(a)});process.on("uncaughtException",a=>{postMessage({oa:"uncaughtException",error:a});process.exit(1)})}var sa;
if(r){var ta=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.oa;if("load"===d){let e=[];self.onmessage=f=>e.push(f);sa=()=>{postMessage({oa:"loaded"});for(let f of e)a(f);self.onmessage=a};for(const f of c.Na)if(!k[f]||k[f].proxy)k[f]=(...g)=>{postMessage({oa:"callHandler",Ma:f,args:g})},"print"==f&&(na=k[f]),"printErr"==f&&(u=k[f]);B=c.Xa;ua();oa=c.Ya;va();wa()}else if("run"===d){xa(c.pa);ya(c.pa,0,0,1,0,0);za();Aa(c.pa);ta||(Ba(),ta=!0);try{Ca(c.Va,c.Ba)}catch(e){if("unwind"!=
e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?ta&&Da():d&&(u(`worker: received unknown command ${d}`),u(c)))}catch(e){throw Ea(),e;}}self.onmessage=a}var B,Fa,C,Ga,D,E,F,Ha,Ia,G,Ja;function ua(){var a=B.buffer;Fa=new Int8Array(a);Ga=new Int16Array(a);C=new Uint8Array(a);D=new Uint16Array(a);E=new Int32Array(a);F=new Uint32Array(a);Ha=new Float32Array(a);Ia=new Float64Array(a);G=new BigInt64Array(a);Ja=new BigUint64Array(a)}function Ka(){r?sa():H.L()}
function La(a){k.onAbort?.(a);a="Aborted("+a+")";u(a);pa=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var Ma;async function Na(a){if(!z)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==Ma&&z)a=new Uint8Array(z);else if(ha)a=ha(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Oa(a,b){try{var c=await Na(a);return await WebAssembly.instantiate(c,b)}catch(d){u(`failed to asynchronously prepare wasm: ${d}`),La(d)}}async function Pa(a){var b=Ma;if(!z&&!ia(b)&&!q)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){u(`wasm streaming compile failed: ${d}`),u("falling back to ArrayBuffer instantiation")}return Oa(b,a)}
function Qa(){Ra={j:Ta,o:Ua,A:Va,w:Wa,u:Xa,J:Ya,f:Za,d:$a,b:ab,c:bb,v:cb,H:db,t:eb,p:fb,g:gb,e:hb,k:ib,I:jb,l:kb,K:lb,E:mb,y:nb,C:ob,z:pb,D:Aa,s:qb,i:rb,n:sb,m:tb,B:ub,F:vb,h:wb,x:xb,G:yb,r:zb,q:Ab,a:B};return{a:Ra}}
async function va(){function a(d,e){H=d.exports;Bb.push(H.S);Cb=H.O;oa=e;d=H;Db=d.M;Ba=d.N;Eb=d.P;Fb=d.Q;k._main=d.R;k.__emscripten_proxy_main=Gb=d.T;ya=d.U;Ea=d.V;I=d.W;Hb=d.X;Ib=d.Y;Jb=d.Z;Kb=d._;Lb=d.$;Mb=d.aa;Nb=d.ba;Ob=d.ca;K--;k.monitorRunDependencies?.(K);0==K&&Pb&&(d=Pb,Pb=null,d());return H}K++;k.monitorRunDependencies?.(K);var b=Qa();if(k.instantiateWasm)new Promise(d=>{k.instantiateWasm(b,(e,f)=>{d(a(e,f))})});else if(r){var c=new WebAssembly.Instance(oa,Qa());a(c,oa)}else Ma??=k.locateFile?
k.locateFile("immolate.wasm",ea):ea+"immolate.wasm",function(d){return a(d.instance,d.module)}(await Pa(b))}class Qb{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var Rb=a=>{a.terminate();a.onmessage=()=>{}},Sb=a=>{for(;0<a.length;)a.shift()(k)},Tb=[],Ub=()=>{var a=k.preRun.shift();Tb.push(a)},Xb=a=>{if(0==L.length){var b=da;k.mainScriptUrlOrBlob&&(b=k.mainScriptUrlOrBlob,"string"!=typeof b&&(b=URL.createObjectURL(b)));b=new Worker(b,{workerData:"em-pthread",name:"em-pthread"});L.push(b);Vb()}b=L.pop();if(!b)return 6;Wb.push(b);M[a.pa]=b;b.pa=a.pa;var c={oa:"run",Va:a.Ua,Ba:a.Ba,pa:a.pa};q&&b.unref();b.postMessage(c,a.Ha);return 0},N=0,yb=()=>O||0<N,Yb=(a,
b,...c)=>{for(var d=2*c.length,e=Ob(),f=Nb(8*d),g=f>>3,h=0;h<c.length;h++){var l=c[h];"bigint"==typeof l?(G[g+2*h]=1n,G[g+2*h+1]=l):(G[g+2*h]=0n,Ia[g+2*h+1]=l)}a=Hb(a,0,d,f,b);Mb(e);return a};function $b(a){if(r)return Yb(0,1,a);qa=a;if(!(O||0<N)){for(var b of Wb)Rb(b);for(b of L)Rb(b);L=[];Wb=[];M={};k.onExit?.(a);pa=!0}ca(a,new Qb(a))}function ac(a){if(r)return Yb(1,0,a);--N;zb(a)}
var zb=a=>{qa=a;if(r)throw ac(a),"unwind";$b(a)},L=[],Wb=[],Bb=[],M={},bc=a=>{var b=a.pa;delete M[b];L.push(a);Wb.splice(Wb.indexOf(a),1);a.pa=0;q&&a.unref();Ib(b)};function za(){Bb.forEach(a=>a())}
var Vb=()=>{var a=L[0];new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.oa;if(g.Aa&&g.Aa!=Eb()){var h=M[g.Aa];h?h.postMessage(g,g.Ha):u(`Internal error! Worker sent a message "${f}" to target pthread ${g.Aa}, but that thread no longer exists!`)}else if("checkMailbox"===f)Da();else if("spawnThread"===f)Xb(g);else if("cleanupThread"===f)cc(()=>{bc(M[g.Wa])});else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("uncaughtException"===f)a.onerror(g.error);else if("callHandler"===
f)k[g.Ma](...g.args);else f&&u(`worker sent an unknown command ${f}`)};a.onerror=f=>{u(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};q&&(a.on("message",f=>a.onmessage({data:f})),a.on("error",f=>a.onerror(f)));var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)k.propertyIsEnumerable(e)&&c.push(e);a.postMessage({oa:"load",Na:c,Xa:B,Ya:oa})})},dc=[],K=0,Pb=null;function xa(a){var b=F[a+52>>2];Lb(b,b-F[a+56>>2]);Mb(b)}
var ec=[],Cb,fc=a=>{var b=ec[a];b||(ec[a]=b=Cb.get(a));return b},Ca=(a,b)=>{O=N=0;a=fc(a)(b);O||0<N?qa=a:Jb(a)},O=!0,gc="undefined"!=typeof TextDecoder?new TextDecoder:void 0,hc=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},ic=(a,b=0,c,d)=>{c=hc(a,b,c,d);if(16<c-b&&a.buffer&&gc)return gc.decode(a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var f=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var g=a[b++]&
63;e=224==(e&240)?(e&15)<<12|f<<6|g:(e&7)<<18|f<<12|g<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},Ta=(a,b,c,d)=>La(`Assertion failed: ${a?ic(C,a):""}, at: `+[b?b?ic(C,b):"":"unknown filename",c,d?d?ic(C,d):"":"unknown function"]);class jc{constructor(a){this.fa=a-24}}var kc=0,lc=0,Ua=(a,b,c)=>{var d=new jc(a);F[d.fa+16>>2]=0;F[d.fa+4>>2]=b;F[d.fa+8>>2]=c;kc=a;lc++;throw kc;};
function mc(a,b,c,d){return r?Yb(2,1,a,b,c,d):Va(a,b,c,d)}var Va=(a,b,c,d)=>{if("undefined"==typeof SharedArrayBuffer)return 6;var e=[];if(r&&0===e.length)return mc(a,b,c,d);a={Ua:c,pa:a,Ba:d,Ha:e};return r?(a.oa="spawnThread",postMessage(a,e),0):Xb(a)},Wa=()=>La(""),R=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},S={},T={},nc={},U=class extends Error{constructor(a){super(a);this.name="BindingError"}},oc=a=>{throw new U(a);};
function pc(a,b,c={}){var d=b.name;if(!a)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(T.hasOwnProperty(a)){if(c.Oa)return;throw new U(`Cannot register type '${d}' twice`);}T[a]=b;delete nc[a];S.hasOwnProperty(a)&&(b=S[a],delete S[a],b.forEach(e=>e()))}function V(a,b,c={}){return pc(a,b,c)}
var qc=(a,b,c)=>{switch(b){case 1:return c?d=>Fa[d]:d=>C[d];case 2:return c?d=>Ga[d>>1]:d=>D[d>>1];case 4:return c?d=>E[d>>2]:d=>F[d>>2];case 8:return c?d=>G[d>>3]:d=>Ja[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Xa=(a,b,c,d,e)=>{b=R(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=h=>BigInt.asUintN(g,h);e=f(e)}V(a,{name:b,ha:f,la:(g,h)=>{"number"==typeof h&&(h=BigInt(h));return h},qa:qc(b,c,!d),na:null})},Ya=(a,b,c,d)=>{b=R(b);V(a,{name:b,ha:function(e){return!!e},la:function(e,
f){return f?c:d},qa:function(e){return this.ha(C[e])},na:null})},rc=a=>{throw new U(a.da.ga.ea.name+" instance already deleted");},sc=!1,tc=()=>{},uc=a=>{if("undefined"===typeof FinalizationRegistry)return uc=b=>b,a;sc=new FinalizationRegistry(b=>{b=b.da;--b.count.value;0===b.count.value&&(b.ja?b.ma.sa(b.ja):b.ga.ea.sa(b.fa))});uc=b=>{var c=b.da;c.ja&&sc.register(b,{da:c},b);return b};tc=b=>{sc.unregister(b)};return uc(a)},vc=[];function wc(){}
var xc=(a,b)=>Object.defineProperty(b,"name",{value:a}),yc={},zc=(a,b,c)=>{if(void 0===a[b].ia){var d=a[b];a[b]=function(...e){if(!a[b].ia.hasOwnProperty(e.length))throw new U(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ia})!`);return a[b].ia[e.length].apply(this,e)};a[b].ia=[];a[b].ia[d.ua]=d}},Ac=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].ia&&void 0!==k[a].ia[c])throw new U(`Cannot register public name '${a}' twice`);zc(k,
a,a);if(k[a].ia.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);k[a].ia[c]=b}else k[a]=b,k[a].ua=c},Bc=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Cc(a,b,c,d,e,f,g,h){this.name=a;this.constructor=b;this.ra=c;this.sa=d;this.ka=e;this.Ka=f;this.xa=g;this.Ja=h;this.Qa=[]}
var Dc=(a,b,c)=>{for(;b!==c;){if(!b.xa)throw new U(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.xa(a);b=b.ka}return a},Ec=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Fc(a,b){if(null===b){if(this.Ca)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.da)throw new U(`Cannot pass "${Ec(b)}" as a ${this.name}`);if(!b.da.fa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);return Dc(b.da.fa,b.da.ga.ea,this.ea)}
function Gc(a,b){if(null===b){if(this.Ca)throw new U(`null is not a valid ${this.name}`);if(this.za){var c=this.Ra();null!==a&&a.push(this.sa,c);return c}return 0}if(!b||!b.da)throw new U(`Cannot pass "${Ec(b)}" as a ${this.name}`);if(!b.da.fa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.da.ga.ya)throw new U(`Cannot convert argument of type ${b.da.ma?b.da.ma.name:b.da.ga.name} to parameter type ${this.name}`);c=Dc(b.da.fa,b.da.ga.ea,this.ea);if(this.za){if(void 0===
b.da.ja)throw new U("Passing raw pointer to smart pointer is illegal");switch(this.Ta){case 0:if(b.da.ma===this)c=b.da.ja;else throw new U(`Cannot convert argument of type ${b.da.ma?b.da.ma.name:b.da.ga.name} to parameter type ${this.name}`);break;case 1:c=b.da.ja;break;case 2:if(b.da.ma===this)c=b.da.ja;else{var d=b.clone();c=this.Sa(c,Hc(()=>d["delete"]()));null!==a&&a.push(this.sa,c)}break;default:throw new U("Unsupporting sharing policy");}}return c}
function Ic(a,b){if(null===b){if(this.Ca)throw new U(`null is not a valid ${this.name}`);return 0}if(!b.da)throw new U(`Cannot pass "${Ec(b)}" as a ${this.name}`);if(!b.da.fa)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.da.ga.ya)throw new U(`Cannot convert argument of type ${b.da.ga.name} to parameter type ${this.name}`);return Dc(b.da.fa,b.da.ga.ea,this.ea)}function Jc(a){return this.ha(F[a>>2])}
var Kc=(a,b,c)=>{if(b===c)return a;if(void 0===c.ka)return null;a=Kc(a,b,c.ka);return null===a?null:c.Ja(a)},Lc={},Mc=(a,b)=>{if(void 0===b)throw new U("ptr should not be undefined");for(;a.ka;)b=a.xa(b),a=a.ka;return Lc[b]},Nc=class extends Error{constructor(a){super(a);this.name="InternalError"}},Oc=(a,b)=>{if(!b.ga||!b.fa)throw new Nc("makeClassHandle requires ptr and ptrType");if(!!b.ma!==!!b.ja)throw new Nc("Both smartPtrType and smartPtr must be specified");b.count={value:1};return uc(Object.create(a,
{da:{value:b,writable:!0}}))};function Pc(a,b,c,d,e,f,g,h,l,n,m){this.name=a;this.ea=b;this.Ca=c;this.ya=d;this.za=e;this.Pa=f;this.Ta=g;this.Ga=h;this.Ra=l;this.Sa=n;this.sa=m;e||void 0!==b.ka?this.la=Gc:(this.la=d?Fc:Ic,this.na=null)}
var Qc=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new Nc("Replacing nonexistent public symbol");void 0!==k[a].ia&&void 0!==c?k[a].ia[c]=b:(k[a]=b,k[a].ua=c)},W=(a,b)=>{a=R(a);var c=fc(b);if("function"!=typeof c)throw new U(`unknown function pointer with signature ${a}: ${b}`);return c};class Rc extends Error{}
var Sc=a=>{a=Db(a);var b=R(a);I(a);return b},X=(a,b)=>{function c(f){e[f]||T[f]||(nc[f]?nc[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new Rc(`${a}: `+d.map(Sc).join([", "]));},Y=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Nc("Mismatched type converter count");for(var l=0;l<a.length;++l)V(a[l],h[l])}a.forEach(h=>nc[h]=b);var e=Array(b.length),f=[],g=0;b.forEach((h,l)=>{T.hasOwnProperty(h)?e[l]=T[h]:(f.push(h),S.hasOwnProperty(h)||(S[h]=[]),S[h].push(()=>
{e[l]=T[h];++g;g===f.length&&d(e)}))});0===f.length&&d(e)},Za=(a,b,c,d,e,f,g,h,l,n,m,t,x)=>{m=R(m);f=W(e,f);h&&=W(g,h);n&&=W(l,n);x=W(t,x);var v=Bc(m);Ac(v,function(){X(`Cannot construct ${m} due to unbound types`,[d])});Y([a,b,c],d?[d]:[],w=>{w=w[0];if(d){var y=w.ea;var P=y.ra}else P=wc.prototype;w=xc(m,function(...Sa){if(Object.getPrototypeOf(this)!==Q)throw new U(`Use 'new' to construct ${m}`);if(void 0===A.ta)throw new U(`${m} has no accessible constructor`);var Zb=A.ta[Sa.length];if(void 0===
Zb)throw new U(`Tried to invoke ctor of ${m} with invalid number of parameters (${Sa.length}) - expected (${Object.keys(A.ta).toString()}) parameters instead!`);return Zb.apply(this,Sa)});var Q=Object.create(P,{constructor:{value:w}});w.prototype=Q;var A=new Cc(m,w,Q,x,y,f,h,n);if(A.ka){var J;(J=A.ka).Da??(J.Da=[]);A.ka.Da.push(A)}y=new Pc(m,A,!0,!1,!1);J=new Pc(m+"*",A,!1,!1,!1);P=new Pc(m+" const*",A,!1,!0,!1);yc[a]={pointerType:J,Ia:P};Qc(v,w);return[y,J,P]})},Tc=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(F[b+
4*d>>2]);return c},Uc=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Vc(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].na)return!0;return!1}
function Wc(a,b,c,d,e,f){var g=b.length;if(2>g)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,l=Vc(b);c=!b[0].Fa;var n=b[0],m=b[1];d=[a,oc,d,e,Uc,n.ha.bind(n),m?.la.bind(m)];for(e=2;e<g;++e)n=b[e],d.push(n.la.bind(n));if(!l)for(e=h?1:2;e<b.length;++e)null!==b[e].na&&d.push(b[e].na);l=Vc(b);e=b.length-2;m=[];n=["fn"];h&&n.push("thisWired");for(g=0;g<e;++g)m.push(`arg${g}`),n.push(`arg${g}Wired`);m=m.join(",");n=n.join(",");
m=`return function (${m}) {\n`;l&&(m+="var destructors = [];\n");var t=l?"destructors":"null",x="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(m+=`var thisWired = toClassParamWire(${t}, this);\n`);for(g=0;g<e;++g){var v=`toArg${g}Wire`;m+=`var arg${g}Wired = ${v}(${t}, arg${g});\n`;x.push(v)}m+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(l)m+="runDestructors(destructors);\n";else for(g=h?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",
null!==b[g].na&&(m+=`${f}_dtor(${f});\n`,x.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(x,m+"}\n"))(...d);return xc(a,b)}
var $a=(a,b,c,d,e,f)=>{var g=Tc(b,c);e=W(d,e);Y([],[a],h=>{h=h[0];var l=`constructor ${h.name}`;void 0===h.ea.ta&&(h.ea.ta=[]);if(void 0!==h.ea.ta[b-1])throw new U(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);h.ea.ta[b-1]=()=>{X(`Cannot construct ${h.name} due to unbound types`,g)};Y([],g,n=>{n.splice(1,0,null);h.ea.ta[b-1]=Wc(l,n,null,e,
f);return[]});return[]})},Xc=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},ab=(a,b,c,d,e,f,g,h,l)=>{var n=Tc(c,d);b=R(b);b=Xc(b);f=W(e,f);Y([],[a],m=>{function t(){X(`Cannot call ${x} due to unbound types`,n)}m=m[0];var x=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&m.ea.Qa.push(b);var v=m.ea.ra,w=v[b];void 0===w||void 0===w.ia&&w.className!==m.name&&w.ua===c-2?(t.ua=c-2,t.className=m.name,v[b]=t):(zc(v,b,x),v[b].ia[c-2]=t);Y([],n,y=>{y=Wc(x,y,m,f,g,l);void 0===
v[b].ia?(y.ua=c-2,v[b]=y):v[b].ia[c-2]=y;return[]});return[]})},Yc=(a,b,c)=>{if(!(a instanceof Object))throw new U(`${c} with invalid "this": ${a}`);if(!(a instanceof b.ea.constructor))throw new U(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.da.fa)throw new U(`cannot call emscripten binding method ${c} on deleted object`);return Dc(a.da.fa,a.da.ga.ea,b.ea)},bb=(a,b,c,d,e,f,g,h,l,n)=>{b=R(b);e=W(d,e);Y([],[a],m=>{m=m[0];var t=`${m.name}.${b}`,x={get(){X(`Cannot access ${t} due to unbound types`,
[c,g])},enumerable:!0,configurable:!0};x.set=l?()=>X(`Cannot access ${t} due to unbound types`,[c,g]):()=>{throw new U(t+" is a read-only property");};Object.defineProperty(m.ea.ra,b,x);Y([],l?[c,g]:[c],v=>{var w=v[0],y={get(){var Q=Yc(this,m,t+" getter");return w.ha(e(f,Q))},enumerable:!0};if(l){l=W(h,l);var P=v[1];y.set=function(Q){var A=Yc(this,m,t+" setter"),J=[];l(n,A,P.la(J,Q));Uc(J)}}Object.defineProperty(m.ea.ra,b,y);return[]});return[]})},cb=(a,b,c)=>{a=R(a);Y([],[b],d=>{d=d[0];k[a]=d.ha(c);
return[]})},Zc=[],Z=[0,1,,1,null,1,!0,1,!1,1],$c=a=>{9<a&&0===--Z[a+1]&&(Z[a]=void 0,Zc.push(a))},ad=a=>{if(!a)throw new U(`Cannot use deleted val. handle = ${a}`);return Z[a]},Hc=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Zc.pop()||Z.length;Z[b]=a;Z[b+1]=1;return b}},bd={name:"emscripten::val",ha:a=>{var b=ad(a);$c(a);return b},la:(a,b)=>Hc(b),qa:Jc,na:null},db=a=>V(a,bd),cd=(a,b)=>{switch(b){case 4:return function(c){return this.ha(Ha[c>>
2])};case 8:return function(c){return this.ha(Ia[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},eb=(a,b,c)=>{b=R(b);V(a,{name:b,ha:d=>d,la:(d,e)=>e,qa:cd(b,c),na:null})},fb=(a,b,c,d,e,f,g)=>{var h=Tc(b,c);a=R(a);a=Xc(a);e=W(d,e);Ac(a,function(){X(`Cannot call ${a} due to unbound types`,h)},b-1);Y([],h,l=>{l=[l[0],null].concat(l.slice(1));Qc(a,Wc(a,l,null,e,f,g),b-1);return[]})},gb=(a,b,c,d,e)=>{b=R(b);let f=h=>h;if(0===d){var g=32-8*c;f=h=>h<<g>>>g;e=f(e)}V(a,{name:b,ha:f,
la:(h,l)=>l,qa:qc(b,c,0!==d),na:null})},hb=(a,b,c)=>{function d(f){return new e(Fa.buffer,F[f+4>>2],F[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c);V(a,{name:c,ha:d,qa:d},{Oa:!0})},dd=Object.assign({optional:!0},bd),ib=a=>{V(a,dd)},jb=(a,b)=>{b=R(b);V(a,{name:b,ha(c){var d=(d=c+4)?ic(C,d,F[c>>2],!0):"";I(c);return d},la(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;
if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var g;if(f)for(e=g=0;e<d.length;++e){var h=d.charCodeAt(e);127>=h?g++:2047>=h?g+=2:55296<=h&&57343>=h?(g+=4,++e):g+=3}else g=d.length;e=g;g=Fb(4+e+1);h=g+4;F[g>>2]=e;if(f){if(f=h,h=e+1,e=C,0<h){h=f+h-1;for(var l=0;l<d.length;++l){var n=d.codePointAt(l);if(127>=n){if(f>=h)break;e[f++]=n}else if(2047>=n){if(f+1>=h)break;e[f++]=192|n>>6;e[f++]=128|n&63}else if(65535>=n){if(f+2>=h)break;e[f++]=
224|n>>12;e[f++]=128|n>>6&63;e[f++]=128|n&63}else{if(f+3>=h)break;e[f++]=240|n>>18;e[f++]=128|n>>12&63;e[f++]=128|n>>6&63;e[f++]=128|n&63;l++}}e[f]=0}}else C.set(d,h);null!==c&&c.push(I,g);return g},qa:Jc,na(c){I(c)}})},ed="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,fd=(a,b,c)=>{a>>=1;b=hc(D,a,b/2,c);if(16<b-a&&ed)return ed.decode(D.buffer instanceof ArrayBuffer?D.subarray(a,b):D.slice(a,b));for(c="";a<b;++a)c+=String.fromCharCode(D[a]);return c},gd=(a,b,c)=>{c??=2147483647;
if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)Ga[b>>1]=a.charCodeAt(e),b+=2;Ga[b>>1]=0;return b-d},hd=a=>2*a.length,jd=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=F[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},kd=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;E[b>>2]=f;b+=4;if(b+4>c)break}E[b>>2]=0;return b-d},ld=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&
c++,b+=4;return b},kb=(a,b,c)=>{c=R(c);if(2===b){var d=fd;var e=gd;var f=hd}else d=jd,e=kd,f=ld;V(a,{name:c,ha:g=>{var h=d(g+4,F[g>>2]*b,!0);I(g);return h},la:(g,h)=>{if("string"!=typeof h)throw new U(`Cannot pass non-string to C++ string type ${c}`);var l=f(h),n=Fb(4+l+b);F[n>>2]=l/b;e(h,n+4,l+b);null!==g&&g.push(I,n);return n},qa:Jc,na(g){I(g)}})},lb=(a,b)=>{b=R(b);V(a,{Fa:!0,name:b,ha:()=>{},la:()=>{}})},mb=a=>{ya(a,!p,1,!aa,65536,!1);za()},md=a=>{a instanceof Qb||"unwind"==a||ca(1,a)},cc=a=>{if(!pa)try{if(a(),
!(O||0<N))try{r?Eb()&&Jb(qa):zb(qa)}catch(b){md(b)}}catch(b){md(b)}},Aa=a=>{"function"===typeof Atomics.waitAsync&&(Atomics.waitAsync(E,a>>2,a).value.then(Da),Atomics.store(E,a+128>>2,1))},Da=()=>cc(()=>{var a=Eb();a&&(Aa(a),Kb())}),nb=(a,b)=>{a==b?setTimeout(Da):r?postMessage({Aa:a,oa:"checkMailbox"}):(a=M[a])&&a.postMessage({oa:"checkMailbox"})},nd=[],ob=(a,b,c,d,e)=>{d/=2;nd.length=d;b=e>>3;for(c=0;c<d;c++)nd[c]=G[b+2*c]?G[b+2*c+1]:Ia[b+2*c+1];return(0,od[a])(...nd)},pb=a=>{r?postMessage({oa:"cleanupThread",
Wa:a}):bc(M[a])},qb=a=>{q&&M[a].ref()},pd=[],qd=a=>{var b=pd.length;pd.push(a);return b},rd=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=F[b+4*d>>2],g=T[f];if(void 0===g)throw a=`${`parameter ${d}`} has unknown type ${Sc(f)}`,new U(a);c[e]=g}return c},sd=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(F[b>>2]=Hc(d));return a},td={},ud=a=>{var b=td[a];return void 0===b?R(a):b},rb=(a,b,c)=>{var [d,...e]=rd(a,b);b=d.la.bind(d);var f=e.map(l=>l.qa.bind(l));a--;var g={toValue:ad};a=f.map((l,n)=>{var m=`argFromPtr${n}`;
g[m]=l;return`${m}(args${n?"+"+8*n:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:g.getStringOrSymbol=ud,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=`(${a})`;d.Fa||(g.toReturnWire=b,g.emval_returnValue=sd,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(g),h))(...Object.values(g));h=`methodCaller<(${e.map(l=>
l.name)}) => ${d.name}>`;return qd(xc(h,c))},sb=(a,b,c,d,e)=>pd[a](b,c,d,e),tb=a=>{var b=ad(a);Uc(b);$c(a)},wb=()=>performance.timeOrigin+performance.now(),ub=()=>{},vb=()=>{N+=1;throw"unwind";},xb=()=>{La("OOM")},vd=[null,[],[]];function Ab(a,b,c,d){if(r)return Yb(3,1,a,b,c,d);for(var e=0,f=0;f<c;f++){var g=F[b>>2],h=F[b+4>>2];b+=8;for(var l=0;l<h;l++){var n=a,m=C[g+l],t=vd[n];0===m||10===m?((1===n?na:u)(ic(t)),t.length=0):t.push(m)}e+=h}F[d>>2]=e;return 0}
(()=>{let a=wc.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof wc&&c instanceof wc))return!1;var d=this.da.ga.ea,e=this.da.fa;c.da=c.da;var f=c.da.ga.ea;for(c=c.da.fa;d.ka;)e=d.xa(e),d=d.ka;for(;f.ka;)c=f.xa(c),f=f.ka;return d===f&&e===c},clone:function(){this.da.fa||rc(this);if(this.da.wa)return this.da.count.value+=1,this;var c=uc,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.da;c=c(e.call(d,f,{da:{value:{count:g.count,va:g.va,wa:g.wa,fa:g.fa,ga:g.ga,ja:g.ja,ma:g.ma}}}));
c.da.count.value+=1;c.da.va=!1;return c},["delete"](){this.da.fa||rc(this);if(this.da.va&&!this.da.wa)throw new U("Object already scheduled for deletion");tc(this);var c=this.da;--c.count.value;0===c.count.value&&(c.ja?c.ma.sa(c.ja):c.ga.ea.sa(c.fa));this.da.wa||(this.da.ja=void 0,this.da.fa=void 0)},isDeleted:function(){return!this.da.fa},deleteLater:function(){this.da.fa||rc(this);if(this.da.va&&!this.da.wa)throw new U("Object already scheduled for deletion");vc.push(this);this.da.va=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(Pc.prototype,{La(a){this.Ga&&(a=this.Ga(a));return a},Ea(a){this.sa?.(a)},qa:Jc,ha:function(a){function b(){return this.za?Oc(this.ea.ra,{ga:this.Pa,fa:c,ma:this,ja:a}):Oc(this.ea.ra,{ga:this,fa:a})}var c=this.La(a);if(!c)return this.Ea(a),null;var d=Mc(this.ea,c);if(void 0!==d){if(0===d.da.count.value)return d.da.fa=c,d.da.ja=a,d.clone();d=d.clone();this.Ea(a);return d}d=this.ea.Ka(c);d=yc[d];if(!d)return b.call(this);d=this.ya?d.Ia:d.pointerType;var e=Kc(c,this.ea,d.ea);return null===
e?b.call(this):this.za?Oc(d.ea.ra,{ga:d,fa:e,ma:this,ja:a}):Oc(d.ea.ra,{ga:d,fa:e})}});if(!r){if(k.wasmMemory)B=k.wasmMemory;else{var wd=k.INITIAL_MEMORY||16777216;B=new WebAssembly.Memory({initial:wd/65536,maximum:wd/65536,shared:!0})}ua()}k.noExitRuntime&&(O=k.noExitRuntime);k.print&&(na=k.print);k.printErr&&(u=k.printErr);k.wasmBinary&&(z=k.wasmBinary);if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();
var od=[$b,ac,mc,Ab],Db,Ba,Eb,Fb,Gb,ya,Ea,I,Hb,Ib,Jb,Kb,Lb,Mb,Nb,Ob,Ra;
function wa(){function a(){k.calledRun=!0;if(!pa){Ka();k.onRuntimeInitialized?.();if(!k.noInitialRun){var b=Gb;N+=1;try{var c=b(0,0);zb(c,!0)}catch(d){md(d)}}if(!r){if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),dc.push(b);Sb(dc)}}}if(0<K)Pb=wa;else if(r)Ka();else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)Ub();Sb(Tb);0<K?Pb=wa:k.setStatus?(k.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>
k.setStatus(""),1);a()},1)):a()}}var H;r||(va(),wa());
