var k;k||=typeof Immolate != 'undefined' ? Immolate : {};var aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,da=(a,b)=>{throw b;},ea="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?ea=__filename:ba&&(ea=self.location.href);var p="",fa,q;
if(ca){var fs=require("fs");p=__dirname+"/";q=a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a)};fa=async a=>{a=r(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);"undefined"!=typeof module&&(module.exports=k);da=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{p=(new URL(".",ea)).href}catch{}ba&&(q=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});fa=async a=>{if(r(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var z=console.error.bind(console),A,ha=!1,r=a=>a.startsWith("file://"),B,ia,C,D,F,G,J,ja,ka,la,ma;
function na(){var a=B.buffer;ia=new Int8Array(a);D=new Int16Array(a);C=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);J=new Uint32Array(a);ja=new Float32Array(a);ka=new Float64Array(a);la=new BigInt64Array(a);ma=new BigUint64Array(a)}function oa(a){k.onAbort?.(a);a="Aborted("+a+")";z(a);ha=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var pa;
async function qa(a){if(!A)try{var b=await fa(a);return new Uint8Array(b)}catch{}if(a==pa&&A)a=new Uint8Array(A);else if(q)a=q(a);else throw"both async and sync fetching of the wasm failed";return a}async function ra(a,b){try{var c=await qa(a);return await WebAssembly.instantiate(c,b)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),oa(d)}}
async function sa(a){var b=pa;if(!A&&!r(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return ra(b,a)}class ta{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}var ua=a=>{for(;0<a.length;)a.shift()(k)},va=[],wa=[],xa=()=>{var a=k.preRun.shift();wa.push(a)},K=0,L=null,za=!0;
class Aa{constructor(a){this.G=a-24}}var Ba=0,Ca=0,M=a=>{for(var b="";;){var c=C[a++];if(!c)return b;b+=String.fromCharCode(c)}},N={},O={},P={},Q=class extends Error{constructor(a){super(a);this.name="BindingError"}},Da=a=>{throw new Q(a);};
function Ea(a,b,c={}){var d=b.name;if(!a)throw new Q(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(a)){if(c.ja)return;throw new Q(`Cannot register type '${d}' twice`);}O[a]=b;delete P[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}function R(a,b,c={}){return Ea(a,b,c)}
var Fa=(a,b,c)=>{switch(b){case 1:return c?d=>ia[d]:d=>C[d];case 2:return c?d=>D[d>>1]:d=>F[d>>1];case 4:return c?d=>G[d>>2]:d=>J[d>>2];case 8:return c?d=>la[d>>3]:d=>ma[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ga=a=>{throw new Q(a.D.H.F.name+" instance already deleted");},Ha=!1,Ia=()=>{},S=a=>{if("undefined"===typeof FinalizationRegistry)return S=b=>b,a;Ha=new FinalizationRegistry(b=>{b=b.D;--b.count.value;0===b.count.value&&(b.K?b.N.S(b.K):b.H.F.S(b.G))});S=b=>
{var c=b.D;c.K&&Ha.register(b,{D:c},b);return b};Ia=b=>{Ha.unregister(b)};return S(a)},Ja=[];function T(){}
var Ka=(a,b)=>Object.defineProperty(b,"name",{value:a}),La={},Ma=(a,b,c)=>{if(void 0===a[b].J){var d=a[b];a[b]=function(...e){if(!a[b].J.hasOwnProperty(e.length))throw new Q(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].J})!`);return a[b].J[e.length].apply(this,e)};a[b].J=[];a[b].J[d.U]=d}},Na=(a,b,c)=>{if(k.hasOwnProperty(a)){if(void 0===c||void 0!==k[a].J&&void 0!==k[a].J[c])throw new Q(`Cannot register public name '${a}' twice`);Ma(k,a,a);if(k[a].J.hasOwnProperty(c))throw new Q(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
k[a].J[c]=b}else k[a]=b,k[a].U=c},Oa=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Pa(a,b,c,d,e,f,h,g){this.name=a;this.constructor=b;this.R=c;this.S=d;this.L=e;this.ha=f;this.X=h;this.ga=g;this.la=[]}
var Qa=(a,b,c)=>{for(;b!==c;){if(!b.X)throw new Q(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.X(a);b=b.L}return a},Ra=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Sa(a,b){if(null===b){if(this.$)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.D)throw new Q(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.D.G)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);return Qa(b.D.G,b.D.H.F,this.F)}
function Ta(a,b){if(null===b){if(this.$)throw new Q(`null is not a valid ${this.name}`);if(this.Z){var c=this.ma();null!==a&&a.push(this.S,c);return c}return 0}if(!b||!b.D)throw new Q(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.D.G)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Y&&b.D.H.Y)throw new Q(`Cannot convert argument of type ${b.D.N?b.D.N.name:b.D.H.name} to parameter type ${this.name}`);c=Qa(b.D.G,b.D.H.F,this.F);if(this.Z){if(void 0===b.D.K)throw new Q("Passing raw pointer to smart pointer is illegal");
switch(this.oa){case 0:if(b.D.N===this)c=b.D.K;else throw new Q(`Cannot convert argument of type ${b.D.N?b.D.N.name:b.D.H.name} to parameter type ${this.name}`);break;case 1:c=b.D.K;break;case 2:if(b.D.N===this)c=b.D.K;else{var d=b.clone();c=this.na(c,Ua(()=>d["delete"]()));null!==a&&a.push(this.S,c)}break;default:throw new Q("Unsupporting sharing policy");}}return c}
function Va(a,b){if(null===b){if(this.$)throw new Q(`null is not a valid ${this.name}`);return 0}if(!b.D)throw new Q(`Cannot pass "${Ra(b)}" as a ${this.name}`);if(!b.D.G)throw new Q(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.D.H.Y)throw new Q(`Cannot convert argument of type ${b.D.H.name} to parameter type ${this.name}`);return Qa(b.D.G,b.D.H.F,this.F)}function Wa(a){return this.I(J[a>>2])}
var Xa=(a,b,c)=>{if(b===c)return a;if(void 0===c.L)return null;a=Xa(a,b,c.L);return null===a?null:c.ga(a)},Ya={},Za=(a,b)=>{if(void 0===b)throw new Q("ptr should not be undefined");for(;a.L;)b=a.X(b),a=a.L;return Ya[b]},$a=class extends Error{constructor(a){super(a);this.name="InternalError"}},ab=(a,b)=>{if(!b.H||!b.G)throw new $a("makeClassHandle requires ptr and ptrType");if(!!b.N!==!!b.K)throw new $a("Both smartPtrType and smartPtr must be specified");b.count={value:1};return S(Object.create(a,
{D:{value:b,writable:!0}}))};function bb(a,b,c,d,e,f,h,g,l,n,m){this.name=a;this.F=b;this.$=c;this.Y=d;this.Z=e;this.ka=f;this.oa=h;this.ea=g;this.ma=l;this.na=n;this.S=m;e||void 0!==b.L?this.M=Ta:(this.M=d?Sa:Va,this.O=null)}
var cb=(a,b,c)=>{if(!k.hasOwnProperty(a))throw new $a("Replacing nonexistent public symbol");void 0!==k[a].J&&void 0!==c?k[a].J[c]=b:(k[a]=b,k[a].U=c)},db=[],eb,U=(a,b)=>{a=M(a);var c;(c=db[b])||(db[b]=c=eb.get(b));if("function"!=typeof c)throw new Q(`unknown function pointer with signature ${a}: ${b}`);return c};class fb extends Error{}
var ib=a=>{a=gb(a);var b=M(a);V(a);return b},W=(a,b)=>{function c(f){e[f]||O[f]||(P[f]?P[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new fb(`${a}: `+d.map(ib).join([", "]));},X=(a,b,c)=>{function d(g){g=c(g);if(g.length!==a.length)throw new $a("Mismatched type converter count");for(var l=0;l<a.length;++l)R(a[l],g[l])}a.forEach(g=>P[g]=b);var e=Array(b.length),f=[],h=0;b.forEach((g,l)=>{O.hasOwnProperty(g)?e[l]=O[g]:(f.push(g),N.hasOwnProperty(g)||(N[g]=[]),N[g].push(()=>{e[l]=
O[g];++h;h===f.length&&d(e)}))});0===f.length&&d(e)},jb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(J[b+4*d>>2]);return c},kb=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function lb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].O)return!0;return!1}
function mb(a,b,c,d,e,f){var h=b.length;if(2>h)throw new Q("argTypes array size mismatch! Must at least get return value and 'this' types!");var g=null!==b[1]&&null!==c,l=lb(b);c=!b[0].da;var n=b[0],m=b[1];d=[a,Da,d,e,kb,n.I.bind(n),m?.M.bind(m)];for(e=2;e<h;++e)n=b[e],d.push(n.M.bind(n));if(!l)for(e=g?1:2;e<b.length;++e)null!==b[e].O&&d.push(b[e].O);l=lb(b);e=b.length-2;m=[];n=["fn"];g&&n.push("thisWired");for(h=0;h<e;++h)m.push(`arg${h}`),n.push(`arg${h}Wired`);m=m.join(",");n=n.join(",");m=`return function (${m}) {\n`;
l&&(m+="var destructors = [];\n");var u=l?"destructors":"null",w="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");g&&(m+=`var thisWired = toClassParamWire(${u}, this);\n`);for(h=0;h<e;++h){var t=`toArg${h}Wire`;m+=`var arg${h}Wired = ${t}(${u}, arg${h});\n`;w.push(t)}m+=(c||f?"var rv = ":"")+`invoker(${n});\n`;if(l)m+="runDestructors(destructors);\n";else for(h=g?1:2;h<b.length;++h)f=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==b[h].O&&(m+=`${f}_dtor(${f});\n`,
w.push(`${f}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(w,m+"}\n"))(...d);return Ka(a,b)}
var nb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},ob=(a,b,c)=>{if(!(a instanceof Object))throw new Q(`${c} with invalid "this": ${a}`);if(!(a instanceof b.F.constructor))throw new Q(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.D.G)throw new Q(`cannot call emscripten binding method ${c} on deleted object`);return Qa(a.D.G,a.D.H.F,b.F)},pb=[],Y=[0,1,,1,null,1,!0,1,!1,1],qb=a=>{9<a&&0===--Y[a+1]&&(Y[a]=void 0,pb.push(a))},rb=a=>{if(!a)throw new Q(`Cannot use deleted val. handle = ${a}`);
return Y[a]},Ua=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=pb.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},sb={name:"emscripten::val",I:a=>{var b=rb(a);qb(a);return b},M:(a,b)=>Ua(b),P:Wa,O:null},tb=(a,b)=>{switch(b){case 4:return function(c){return this.I(ja[c>>2])};case 8:return function(c){return this.I(ka[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},ub=Object.assign({optional:!0},sb),vb="undefined"!=typeof TextDecoder?
new TextDecoder:void 0,wb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},xb=(a=0,b)=>{var c=C;b=wb(c,a,b,!0);if(16<b-a&&c.buffer&&vb)return vb.decode(c.subarray(a,b));for(var d="";a<b;){var e=c[a++];if(e&128){var f=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|f);else{var h=c[a++]&63;e=224==(e&240)?(e&15)<<12|f<<6|h:(e&7)<<18|f<<12|h<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
yb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,zb=(a,b,c)=>{a>>=1;b=wb(F,a,b/2,c);if(16<b-a&&yb)return yb.decode(F.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(F[a]);return c},Ab=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)D[b>>1]=a.charCodeAt(e),b+=2;D[b>>1]=0;return b-d},Bb=a=>2*a.length,Cb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=J[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},
Db=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;G[b>>2]=f;b+=4;if(b+4>c)break}G[b>>2]=0;return b-d},Eb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Fb=[],Gb=a=>{var b=Fb.length;Fb.push(a);return b},Hb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=J[b+4*d>>2],h=O[f];if(void 0===h)throw a=`${`parameter ${d}`} has unknown type ${ib(f)}`,new Q(a);c[e]=h}return c},Ib=(a,b,c)=>{var d=[];a=a(d,
c);d.length&&(J[b>>2]=Ua(d));return a},Jb={},Kb=a=>{var b=Jb[a];return void 0===b?M(a):b};
(()=>{let a=T.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof T&&c instanceof T))return!1;var d=this.D.H.F,e=this.D.G;c.D=c.D;var f=c.D.H.F;for(c=c.D.G;d.L;)e=d.X(e),d=d.L;for(;f.L;)c=f.X(c),f=f.L;return d===f&&e===c},clone:function(){this.D.G||Ga(this);if(this.D.W)return this.D.count.value+=1,this;var c=S,d=Object,e=d.create,f=Object.getPrototypeOf(this),h=this.D;c=c(e.call(d,f,{D:{value:{count:h.count,V:h.V,W:h.W,G:h.G,H:h.H,K:h.K,N:h.N}}}));c.D.count.value+=1;c.D.V=!1;return c},
["delete"](){this.D.G||Ga(this);if(this.D.V&&!this.D.W)throw new Q("Object already scheduled for deletion");Ia(this);var c=this.D;--c.count.value;0===c.count.value&&(c.K?c.N.S(c.K):c.H.F.S(c.G));this.D.W||(this.D.K=void 0,this.D.G=void 0)},isDeleted:function(){return!this.D.G},deleteLater:function(){this.D.G||Ga(this);if(this.D.V&&!this.D.W)throw new Q("Object already scheduled for deletion");Ja.push(this);this.D.V=!0;return this}});const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(bb.prototype,{ia(a){this.ea&&(a=this.ea(a));return a},ba(a){this.S?.(a)},P:Wa,I:function(a){function b(){return this.Z?ab(this.F.R,{H:this.ka,G:c,N:this,K:a}):ab(this.F.R,{H:this,G:a})}var c=this.ia(a);if(!c)return this.ba(a),null;var d=Za(this.F,c);if(void 0!==d){if(0===d.D.count.value)return d.D.G=c,d.D.K=a,d.clone();d=d.clone();this.ba(a);return d}d=this.F.ha(c);d=La[d];if(!d)return b.call(this);d=this.Y?d.fa:d.pointerType;var e=Xa(c,this.F,d.F);return null===e?b.call(this):this.Z?
ab(d.F.R,{H:d,G:e,N:this,K:a}):ab(d.F.R,{H:d,G:e})}});k.noExitRuntime&&(za=k.noExitRuntime);k.printErr&&(z=k.printErr);k.wasmBinary&&(A=k.wasmBinary);if(k.preInit)for("function"==typeof k.preInit&&(k.preInit=[k.preInit]);0<k.preInit.length;)k.preInit.shift()();
var gb,Lb,Mb,V,Nb={l:(a,b,c)=>{var d=new Aa(a);J[d.G+16>>2]=0;J[d.G+4>>2]=b;J[d.G+8>>2]=c;Ba=a;Ca++;throw Ba;},q:()=>oa(""),o:(a,b,c,d,e)=>{b=M(b);d=0n===d;let f=h=>h;if(d){const h=8*c;f=g=>BigInt.asUintN(h,g);e=f(e)}R(a,{name:b,I:f,M:(h,g)=>{"number"==typeof g&&(g=BigInt(g));return g},P:Fa(b,c,!d),O:null})},u:(a,b,c,d)=>{b=M(b);R(a,{name:b,I:function(e){return!!e},M:function(e,f){return f?c:d},P:function(e){return this.I(C[e])},O:null})},e:(a,b,c,d,e,f,h,g,l,n,m,u,w)=>{m=M(m);f=U(e,f);g&&=U(h,g);
n&&=U(l,n);w=U(u,w);var t=Oa(m);Na(t,function(){W(`Cannot construct ${m} due to unbound types`,[d])});X([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.F;var H=x.R}else H=T.prototype;v=Ka(m,function(...ya){if(Object.getPrototypeOf(this)!==I)throw new Q(`Use 'new' to construct ${m}`);if(void 0===y.T)throw new Q(`${m} has no accessible constructor`);var hb=y.T[ya.length];if(void 0===hb)throw new Q(`Tried to invoke ctor of ${m} with invalid number of parameters (${ya.length}) - expected (${Object.keys(y.T).toString()}) parameters instead!`);
return hb.apply(this,ya)});var I=Object.create(H,{constructor:{value:v}});v.prototype=I;var y=new Pa(m,v,I,w,x,f,g,n);if(y.L){var E;(E=y.L).aa??(E.aa=[]);y.L.aa.push(y)}x=new bb(m,y,!0,!1,!1);E=new bb(m+"*",y,!1,!1,!1);H=new bb(m+" const*",y,!1,!0,!1);La[a]={pointerType:E,fa:H};cb(t,v);return[x,E,H]})},c:(a,b,c,d,e,f)=>{var h=jb(b,c);e=U(d,e);X([],[a],g=>{g=g[0];var l=`constructor ${g.name}`;void 0===g.F.T&&(g.F.T=[]);if(void 0!==g.F.T[b-1])throw new Q(`Cannot register multiple constructors with identical number of parameters (${b-
1}) for class '${g.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);g.F.T[b-1]=()=>{W(`Cannot construct ${g.name} due to unbound types`,h)};X([],h,n=>{n.splice(1,0,null);g.F.T[b-1]=mb(l,n,null,e,f);return[]});return[]})},a:(a,b,c,d,e,f,h,g,l)=>{var n=jb(c,d);b=M(b);b=nb(b);f=U(e,f);X([],[a],m=>{function u(){W(`Cannot call ${w} due to unbound types`,n)}m=m[0];var w=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);g&&m.F.la.push(b);
var t=m.F.R,v=t[b];void 0===v||void 0===v.J&&v.className!==m.name&&v.U===c-2?(u.U=c-2,u.className=m.name,t[b]=u):(Ma(t,b,w),t[b].J[c-2]=u);X([],n,x=>{x=mb(w,x,m,f,h,l);void 0===t[b].J?(x.U=c-2,t[b]=x):t[b].J[c-2]=x;return[]});return[]})},b:(a,b,c,d,e,f,h,g,l,n)=>{b=M(b);e=U(d,e);X([],[a],m=>{m=m[0];var u=`${m.name}.${b}`,w={get(){W(`Cannot access ${u} due to unbound types`,[c,h])},enumerable:!0,configurable:!0};w.set=l?()=>W(`Cannot access ${u} due to unbound types`,[c,h]):()=>{throw new Q(u+" is a read-only property");
};Object.defineProperty(m.F.R,b,w);X([],l?[c,h]:[c],t=>{var v=t[0],x={get(){var I=ob(this,m,u+" getter");return v.I(e(f,I))},enumerable:!0};if(l){l=U(g,l);var H=t[1];x.set=function(I){var y=ob(this,m,u+" setter"),E=[];l(n,y,H.M(E,I));kb(E)}}Object.defineProperty(m.F.R,b,x);return[]});return[]})},p:(a,b,c)=>{a=M(a);X([],[b],d=>{d=d[0];k[a]=d.I(c);return[]})},s:a=>R(a,sb),n:(a,b,c)=>{b=M(b);R(a,{name:b,I:d=>d,M:(d,e)=>e,P:tb(b,c),O:null})},m:(a,b,c,d,e,f,h)=>{var g=jb(b,c);a=M(a);a=nb(a);e=U(d,e);Na(a,
function(){W(`Cannot call ${a} due to unbound types`,g)},b-1);X([],g,l=>{l=[l[0],null].concat(l.slice(1));cb(a,mb(a,l,null,e,f,h),b-1);return[]})},f:(a,b,c,d,e)=>{b=M(b);let f=g=>g;if(0===d){var h=32-8*c;f=g=>g<<h>>>h;e=f(e)}R(a,{name:b,I:f,M:(g,l)=>l,P:Fa(b,c,0!==d),O:null})},d:(a,b,c)=>{function d(f){return new e(ia.buffer,J[f+4>>2],J[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=M(c);R(a,{name:c,I:d,
P:d},{ja:!0})},i:a=>{R(a,ub)},t:(a,b)=>{b=M(b);R(a,{name:b,I(c){var d=(d=c+4)?xb(d,J[c>>2]):"";V(c);return d},M(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,f="string"==typeof d;if(!(f||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new Q("Cannot pass non-string to std::string");var h;if(f)for(e=h=0;e<d.length;++e){var g=d.charCodeAt(e);127>=g?h++:2047>=g?h+=2:55296<=g&&57343>=g?(h+=4,++e):h+=3}else h=d.length;e=h;h=Lb(4+e+1);g=h+4;J[h>>2]=e;if(f){if(f=g,g=e+1,e=C,0<g){g=f+g-1;
for(var l=0;l<d.length;++l){var n=d.codePointAt(l);if(127>=n){if(f>=g)break;e[f++]=n}else if(2047>=n){if(f+1>=g)break;e[f++]=192|n>>6;e[f++]=128|n&63}else if(65535>=n){if(f+2>=g)break;e[f++]=224|n>>12;e[f++]=128|n>>6&63;e[f++]=128|n&63}else{if(f+3>=g)break;e[f++]=240|n>>18;e[f++]=128|n>>12&63;e[f++]=128|n>>6&63;e[f++]=128|n&63;l++}}e[f]=0}}else C.set(d,g);null!==c&&c.push(V,h);return h},P:Wa,O(c){V(c)}})},j:(a,b,c)=>{c=M(c);if(2===b){var d=zb;var e=Ab;var f=Bb}else d=Cb,e=Db,f=Eb;R(a,{name:c,I:h=>
{var g=d(h+4,J[h>>2]*b,!0);V(h);return g},M:(h,g)=>{if("string"!=typeof g)throw new Q(`Cannot pass non-string to C++ string type ${c}`);var l=f(g),n=Lb(4+l+b);J[n>>2]=l/b;e(g,n+4,l+b);null!==h&&h.push(V,n);return n},P:Wa,O(h){V(h)}})},v:(a,b)=>{b=M(b);R(a,{da:!0,name:b,I:()=>{},M:()=>{}})},h:(a,b,c)=>{var [d,...e]=Hb(a,b);b=d.M.bind(d);var f=e.map(l=>l.P.bind(l));a--;var h={toValue:rb};a=f.map((l,n)=>{var m=`argFromPtr${n}`;h[m]=l;return`${m}(args${n?"+"+8*n:""})`});switch(c){case 0:var g="toValue(handle)";
break;case 2:g="new (toValue(handle))";break;case 3:g="";break;case 1:h.getStringOrSymbol=Kb,g="toValue(handle)[getStringOrSymbol(methodName)]"}g+=`(${a})`;d.da||(h.toReturnWire=b,h.emval_returnValue=Ib,g=`return emval_returnValue(toReturnWire, destructorsRef, ${g})`);g=`return function (handle, methodName, destructorsRef, args) {\n  ${g}\n  }`;c=(new Function(Object.keys(h),g))(...Object.values(h));g=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return Gb(Ka(g,c))},g:(a,b,c,d,e)=>Fb[a](b,c,
d,e),k:a=>{var b=rb(a);kb(b);qb(a)},r:a=>{var b=C.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-B.buffer.byteLength+65535)/65536|0;try{B.grow(d);na();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1}};
function Ob(){function a(){k.calledRun=!0;if(!ha){Z.x();k.onRuntimeInitialized?.();if(!k.noInitialRun){var b=Mb;try{var c=b(0,0);za||(k.onExit?.(c),ha=!0);da(c,new ta(c))}catch(d){d instanceof ta||"unwind"==d||da(1,d)}}if(k.postRun)for("function"==typeof k.postRun&&(k.postRun=[k.postRun]);k.postRun.length;)b=k.postRun.shift(),va.push(b);ua(va)}}if(0<K)L=Ob;else{if(k.preRun)for("function"==typeof k.preRun&&(k.preRun=[k.preRun]);k.preRun.length;)xa();ua(wa);0<K?L=Ob:k.setStatus?(k.setStatus("Running..."),
setTimeout(()=>{setTimeout(()=>k.setStatus(""),1);a()},1)):a()}}var Z;(async function(){function a(c){Z=c.exports;B=Z.w;na();eb=Z.z;c=Z;gb=c.y;Lb=c.A;k._main=Mb=c.B;V=c.C;K--;k.monitorRunDependencies?.(K);0==K&&L&&(c=L,L=null,c());return Z}K++;k.monitorRunDependencies?.(K);var b={a:Nb};if(k.instantiateWasm)return new Promise(c=>{k.instantiateWasm(b,(d,e)=>{c(a(d,e))})});pa??=k.locateFile?k.locateFile("immolate.wasm",p):p+"immolate.wasm";return a((await sa(b)).instance)})();Ob();
